audio:
  chunk_size: 393216
  dim_f: 2049
  dim_t: 384
  hop_length: 1024
  n_fft: 4096
  num_channels: 2
  sample_rate: 44100
  win_length: 4096
  center: true
  pad_mode: reflect

model:
  type: moises_light
  args:
    n_bands: 4
    n_enc: 3
    n_dec: 1
    n_rope: 5
    n_split_enc: 3
    n_split_dec: 1
    g: 48
    dropout: 0.1
    num_stems: 1
    audio_channels: 2
    n_fft: 4096
    hop_length: 1024
    win_length: 4096
    mask_activation: sigmoid

training:
  batch_size: 8
  gradient_accumulation_steps: 4
  grad_clip: null
  instruments:
    - vocals
    - drums
    - bass
    - other
  target_instrument: other
  lr: 5.0e-04
  optimizer: adamw
  scheduler: ReduceLROnPlateau
  patience: 50
  reduce_factor: 0.5
  num_epochs: 1000
  num_steps: 1000
  loss_function: multi_resolution_mae
  window_sizes:
    - 4096
    - 2048
    - 1024
    - 512
    - 256
  hop_size: 147
  normalize: true
  ema_momentum: 0.999
  use_amp: true

augmentations:
  enable: true
  mixup: true
  mixup_probs: !!python/tuple
    - 0.2
  mixup_loudness_min: 0.7
  mixup_loudness_max: 1.3
  all:
    channel_shuffle: 0.1
    random_polarity: 0.1

inference:
  batch_size: 1
  dim_t: 384
  num_overlap: 4
