audio:
  chunk_size: 393216
  dim_f: 2049
  dim_t: 384
  hop_length: 1024
  n_fft: 4096
  num_channels: 2
  sample_rate: 44100
  win_length: 6144
  center: true
  pad_mode: reflect

model:
  type: moises_light
  args:
    n_bands: 4
    n_enc: 3
    n_dec: 1
    n_rope: 5
    n_split_enc: 3
    n_split_dec: 1
    g: 48
    dropout: 0.1
    num_stems: 1
    audio_channels: 2
    n_fft: 4096
    hop_length: 1024
    win_length: 6144
    crop_freq_bins: 2048
    mask_activation: sigmoid
    center: true

training:
  batch_size: 8
  gradient_accumulation_steps: 4
  grad_clip: null
  instruments:
    - vocals
    - other
  target_instrument: vocals
  lr: 2.0e-04
  optimizer: adamw
  lr_scheduler:
    type: plateau_decay
    patience: 20
    factor: 0.9
  early_stopping:
    patience: 50
  num_epochs: 1000
  num_steps: 1000
  loss_function: multi_resolution_mae
  stft_setups:
    - n_fft: 4096
      win_length: 6144
      hop_length: 1024
    - n_fft: 3072
      win_length: 4096
      hop_length: 768
    - n_fft: 2048
      win_length: 3072
      hop_length: 512
  normalize: true
  ema_momentum: 0.999
  use_amp: true

augmentations:
  enable: false
  polarity_inversion:
    prob: 0.5
  pitch_shift:
    prob: 0.3
    semitone_range:
      - -2
      - 2
  temporal_shift:
    prob: 0.3
    max_shift: 0.2
  channel_flip:
    prob: 0.25

inference:
  batch_size: 1
  dim_t: 384
  overlap_add: true
  overlap_ratio: 0.5
